logging:
  level:
    root: INFO
#------spring
spring:
  application:
    name: app-peoplety-im
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
server:
  port: 8200
  servlet:
    context-path: "/"
eureka:
  client:
    serviceUrl:
      defaultZone: http://gaozhi.online:8080/eureka/
  instance:
    instance-id: peoplety-im
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true
# ---- imConfig
imConfig:
  udpPort: 7901
  tcpPort: 8901
  webSocketPort: 9901
  loginURL: im://gaozhi.online/general/login
  failedURL: im://gaozhi.online/general/failed